### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by emilyastranova** [TrevTV/instantcfdownload#1]
I think CurseForge may have updated. Countdown persists.

**Comment by TrevTV** [comment]
Yep, the countdown page's URL no longer contains the mod ID. There may be some place that it is still stored and I may be able to fix it using that.

Edit: Looking through a bit more, downloading from the "Recent Files" panel still seems to work, I will still try to get the top download button to work though.

**Comment by emilyastranova** [comment]
I've never written any scripts before, but after some testing it seems I've got it working. I just submitted a pull request.

**Comment by TrevTV** [comment]
Merged

**Comment by emilyastranova** [comment]
Very cool. Thanks!
